language: elixir
elixir:
  - 1.9
addons: # ensure that Travis-CI provisions a DB for our test:
  postgresql: '9.5'
env:
  global:
    - MIX_ENV=test
    - GITHUB_CLIENT_ID=d6fca75c63daa014c187
    - GITHUB_CLIENT_SECRET=8eeb143935d1a505692aaef856db9b4da8245f3c
script:
  - mix do deps.get, test
